-- Insert sample ingredients
INSERT INTO ingredients (name) VALUES 
('chicken breast'),
('olive oil'),
('garlic'),
('onion'),
('tomatoes'),
('pasta'),
('basil'),
('parmesan cheese'),
('salt'),
('black pepper'),
('rice'),
('soy sauce'),
('ginger'),
('carrots'),
('bell peppers'),
('beef'),
('potatoes'),
('milk'),
('butter'),
('flour'),
('eggs'),
('bacon'),
('lettuce'),
('cucumber'),
('lemon'),
('lime'),
('cilantro'),
('cumin'),
('chili powder'),
('tortillas'),
('cheese'),
('mushrooms'),
('spinach'),
('cream'),
('shrimp'),
('fish'),
('bread'),
('mayonnaise'),
('mustard'),
('avocado'),
('corn'),
('beans'),
('chicken broth'),
('bay leaves'),
('thyme'),
('rosemary'),
('oregano'),
('cinnamon'),
('nutmeg'),
('vanilla extract'),
('chocolate'),
('sugar'),
('baking powder'),
('baking soda'),
('coconut milk'),
('curry powder'),
('turmeric'),
('yogurt'),
('mint'),
('honey'),
('almonds'),
('walnuts'),
('raisins'),
('coconut'),
('lentils'),
('chickpeas'),
('feta cheese'),
('olives'),
('eggplant'),
('zucchini'),
('broccoli'),
('cauliflower'),
('green beans'),
('asparagus'),
('mango'),
('pineapple'),
('strawberries'),
('blueberries'),
('apples'),
('bananas'),
('pears'),
('peaches'),
('plums'),
('dates'),
('figs'),
('pomegranate'),
('quinoa'),
('couscous'),
('bulgur'),
('barley'),
('oats'),
('almond milk'),
('soy milk'),
('maple syrup'),
('agave nectar'),
('chia seeds'),
('flax seeds'),
('sunflower seeds'),
('pumpkin seeds'),
('sesame seeds'),
('poppy seeds'),
('cayenne pepper'),
('paprika'),
('cardamom'),
('cloves'),
('allspice'),
('star anise'),
('lemongrass'),
('fish sauce'),
('oyster sauce'),
('hoisin sauce'),
('sesame oil'),
('rice vinegar'),
('balsamic vinegar'),
('red wine vinegar'),
('white wine'),
('red wine'),
('beer'),
('sake'),
('mirin'),
('worcestershire sauce'),
('anchovies'),
('capers'),
('sun-dried tomatoes'),
('artichokes'),
('asparagus'),
('mushrooms'),
('truffles'),
('saffron'),
('wasabi'),
('miso'),
('tempeh'),
('tofu'),
('seitan'),
('nutritional yeast'),
('tahini'),
('hummus'),
('guacamole'),
('salsa'),
('pico de gallo'),
('sour cream'),
('cream cheese'),
('ricotta cheese'),
('mozzarella'),
('cheddar'),
('gouda'),
('brie'),
('camembert'),
('provolone'),
('swiss cheese'),
('blue cheese'),
('goat cheese'),
('halloumi'),
('paneer'),
('tempeh'),
('tofu'),
('seitan'),
('nutritional yeast'),
('tahini'),
('hummus'),
('guacamole'),
('salsa'),
('pico de gallo'),
('sour cream'),
('cream cheese'),
('ricotta cheese'),
('mozzarella'),
('cheddar'),
('gouda'),
('brie'),
('camembert'),
('provolone'),
('swiss cheese'),
('blue cheese'),
('goat cheese'),
('halloumi'),
('paneer');

-- Insert sample recipes
INSERT INTO recipes (title, description, instructions, cooking_time, servings, image_url) VALUES
('Classic Spaghetti with Tomato Sauce', 
'A delicious Italian pasta dish with fresh tomato sauce', 
'1. Boil pasta according to package instructions\n2. Heat olive oil in a pan\n3. Sauté garlic and onions until fragrant\n4. Add tomatoes and cook for 15 minutes\n5. Season with salt and pepper\n6. Add fresh basil\n7. Serve with grated parmesan',
30, 4, 
'images/spaghetti.jpg'),

('Chicken Stir Fry', 
'Quick and easy Asian-inspired chicken stir fry', 
'1. Cut chicken into bite-sized pieces\n2. Heat oil in a wok\n3. Cook chicken until golden\n4. Add vegetables and stir fry\n5. Add soy sauce and ginger\n6. Serve hot with rice',
25, 3, 
'images/stir-fry.jpg'),

('Beef Wellington',
'Classic British dish with tender beef wrapped in pastry',
'1. Season beef tenderloin\n2. Sear beef on all sides\n3. Layer with mushroom duxelles\n4. Wrap in prosciutto\n5. Encase in puff pastry\n6. Bake until golden brown',
60, 4,
'images/beef-wellington.jpg'),

('Vegetarian Buddha Bowl',
'Healthy and nutritious bowl packed with protein-rich ingredients',
'1. Cook quinoa\n2. Roast vegetables\n3. Prepare chickpeas\n4. Make tahini dressing\n5. Assemble bowl with fresh greens\n6. Top with seeds and dressing',
35, 2,
'images/buddha-bowl.jpg'),

('Thai Green Curry',
'Authentic Thai curry with coconut milk and fresh herbs',
'1. Make green curry paste\n2. Cook curry paste in oil\n3. Add coconut milk\n4. Simmer with vegetables\n5. Add protein of choice\n6. Season with fish sauce and lime',
40, 4,
'images/green-curry.jpg'),

('Mediterranean Grilled Fish',
'Light and healthy grilled fish with Mediterranean flavors',
'1. Marinate fish in herbs and lemon\n2. Prepare Mediterranean vegetables\n3. Grill fish until cooked\n4. Serve with vegetables and tzatziki',
30, 2,
'images/grilled-fish.jpg'),

('Homemade Pizza',
'Classic Italian pizza with fresh toppings',
'1. Make pizza dough\n2. Prepare tomato sauce\n3. Add toppings\n4. Bake in hot oven\n5. Garnish with fresh basil',
45, 4,
'images/pizza.jpg'),

('Indian Butter Chicken',
'Creamy and rich Indian curry with tender chicken',
'1. Marinate chicken in spiced yogurt\n2. Cook chicken until tender\n3. Prepare butter sauce\n4. Combine and simmer\n5. Garnish with cream and cilantro',
50, 4,
'images/butter-chicken.jpg'),

('Mexican Enchiladas',
'Cheesy enchiladas with spicy sauce',
'1. Prepare enchilada sauce\n2. Fill tortillas with filling\n3. Roll enchiladas\n4. Top with sauce and cheese\n5. Bake until bubbly',
40, 4,
'images/enchiladas.jpg'),

('Greek Moussaka',
'Layered eggplant casserole with spiced meat sauce',
'1. Fry eggplant slices\n2. Prepare meat sauce\n3. Make béchamel sauce\n4. Layer ingredients\n5. Bake until golden',
60, 6,
'images/moussaka.jpg'),

('Japanese Ramen',
'Hearty noodle soup with rich broth',
'1. Prepare ramen broth\n2. Cook noodles\n3. Prepare toppings\n4. Assemble bowl\n5. Add garnishes',
45, 4,
'images/ramen.jpg'),

('Moroccan Tagine',
'Slow-cooked stew with aromatic spices',
'1. Brown meat\n2. Add vegetables and spices\n3. Slow cook until tender\n4. Add dried fruits\n5. Garnish with herbs',
90, 6,
'images/tagine.jpg'),

('Creamy White Sauce Pasta', 
'Classic Italian pasta in rich bechamel sauce with mushrooms', 
'1. Cook pasta according to package instructions\n2. In a pan, melt butter over medium heat\n3. Add flour and cook for 2 minutes\n4. Gradually whisk in milk until smooth\n5. Add garlic, mushrooms, and cook until sauce thickens\n6. Season with salt, pepper, and nutmeg\n7. Add cooked pasta and parmesan\n8. Garnish with parsley',
25, 4, 
'images/white-sauce-pasta.jpg'),

('Classic Marinara Pasta',
'Traditional Italian red sauce pasta with fresh herbs', 
'1. Heat olive oil in a large pan\n2. Sauté garlic and onions until golden\n3. Add crushed tomatoes and tomato paste\n4. Add Italian herbs and red pepper flakes\n5. Simmer sauce for 20 minutes\n6. Cook pasta until al dente\n7. Combine pasta with sauce\n8. Top with fresh basil and parmesan',
30, 4,
'images/marinara-pasta.jpg'),
('Masala Dosa', 
'Crispy South Indian crepe filled with spiced potato mixture', 
'1. Soak rice and urad dal for 6 hours\n2. Grind into smooth batter and ferment overnight\n3. For potato filling: cook potatoes and mash\n4. Sauté onions, mustard seeds, curry leaves\n5. Add mashed potatoes and spices\n6. Heat dosa pan and spread batter in circular motion\n7. Add oil and cook until crispy\n8. Place potato filling and fold\n9. Serve with coconut chutney and sambar',
45, 4, 
'images/masala-dosa.jpg'),

('Hyderabadi Chicken Biryani',
'Aromatic layered rice dish with marinated chicken and saffron', 
'1. Marinate chicken with yogurt, ginger-garlic paste, and spices\n2. Soak basmati rice and cook with whole spices\n3. In a heavy bottom pot, layer half-cooked rice and marinated chicken\n4. Add saffron milk, fried onions, and mint leaves\n5. Seal pot with dough and cook on low heat\n6. Steam for 20 minutes\n7. Let it rest for 10 minutes\n8. Serve hot with raita',
60, 6,
'images/biryani.jpg'),

('Rice Pudding',
'Creamy and comforting rice pudding with warm spices',
'1. Cook rice with whole spices\n2. Add milk, sugar, and cardamom\n3. Cook until creamy\n4. Garnish with almonds, raisins, and saffron',
30, 4,
'images/rice-pudding.jpg');

-- First clear existing data
DELETE FROM recipe_ingredients;

-- Link recipes with ingredients
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity) VALUES
-- Recipe 1: Classic Spaghetti with Tomato Sauce
(1, (SELECT id FROM ingredients WHERE name = 'pasta'), '500g'),
(1, (SELECT id FROM ingredients WHERE name = 'olive oil'), '3 tablespoons'),
(1, (SELECT id FROM ingredients WHERE name = 'garlic'), '3 cloves'),
(1, (SELECT id FROM ingredients WHERE name = 'onion'), '1 medium'),
(1, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '4 large'),
(1, (SELECT id FROM ingredients WHERE name = 'basil'), '1/2 cup'),
(1, (SELECT id FROM ingredients WHERE name = 'parmesan cheese'), '1/2 cup'),
(1, (SELECT id FROM ingredients WHERE name = 'salt'), 'to taste'),
(1, (SELECT id FROM ingredients WHERE name = 'black pepper'), 'to taste'),

-- Recipe 2: Chicken Stir Fry
(2, (SELECT id FROM ingredients WHERE name = 'chicken breast'), '500g'),
(2, (SELECT id FROM ingredients WHERE name = 'olive oil'), '2 tablespoons'),
(2, (SELECT id FROM ingredients WHERE name = 'garlic'), '2 cloves'),
(2, (SELECT id FROM ingredients WHERE name = 'carrots'), '2 medium'),
(2, (SELECT id FROM ingredients WHERE name = 'bell peppers'), '2 medium'),
(2, (SELECT id FROM ingredients WHERE name = 'soy sauce'), '3 tablespoons'),
(2, (SELECT id FROM ingredients WHERE name = 'ginger'), '1 tablespoon'),
(2, (SELECT id FROM ingredients WHERE name = 'rice'), '2 cups'),

-- Recipe 3: Beef Wellington
(3, (SELECT id FROM ingredients WHERE name = 'beef'), '800g'),
(3, (SELECT id FROM ingredients WHERE name = 'mushrooms'), '300g'),
(3, (SELECT id FROM ingredients WHERE name = 'flour'), '2 cups'),
(3, (SELECT id FROM ingredients WHERE name = 'butter'), '200g'),
(3, (SELECT id FROM ingredients WHERE name = 'eggs'), '2'),
(3, (SELECT id FROM ingredients WHERE name = 'thyme'), '2 tablespoons'),
(3, (SELECT id FROM ingredients WHERE name = 'salt'), 'to taste'),
(3, (SELECT id FROM ingredients WHERE name = 'black pepper'), 'to taste'),

-- Recipe 4: Vegetarian Buddha Bowl
(4, (SELECT id FROM ingredients WHERE name = 'quinoa'), '1 cup'),
(4, (SELECT id FROM ingredients WHERE name = 'chickpeas'), '1 can'),
(4, (SELECT id FROM ingredients WHERE name = 'sweet potatoes'), '2 medium'),
(4, (SELECT id FROM ingredients WHERE name = 'avocado'), '1'),
(4, (SELECT id FROM ingredients WHERE name = 'spinach'), '2 cups'),
(4, (SELECT id FROM ingredients WHERE name = 'olive oil'), '2 tablespoons'),
(4, (SELECT id FROM ingredients WHERE name = 'lemon'), '1'),
(4, (SELECT id FROM ingredients WHERE name = 'tahini'), '3 tablespoons'),

-- Recipe 5: Thai Green Curry
(5, (SELECT id FROM ingredients WHERE name = 'chicken breast'), '600g'),
(5, (SELECT id FROM ingredients WHERE name = 'coconut milk'), '2 cans'),
(5, (SELECT id FROM ingredients WHERE name = 'green curry paste'), '3 tablespoons'),
(5, (SELECT id FROM ingredients WHERE name = 'fish sauce'), '2 tablespoons'),
(5, (SELECT id FROM ingredients WHERE name = 'bell peppers'), '2'),
(5, (SELECT id FROM ingredients WHERE name = 'bamboo shoots'), '1 can'),
(5, (SELECT id FROM ingredients WHERE name = 'basil'), '1 cup'),
(5, (SELECT id FROM ingredients WHERE name = 'rice'), '2 cups'),

-- Recipe 6: Mediterranean Grilled Fish
(6, (SELECT id FROM ingredients WHERE name = 'fish'), '4 fillets'),
(6, (SELECT id FROM ingredients WHERE name = 'lemon'), '2'),
(6, (SELECT id FROM ingredients WHERE name = 'olive oil'), '1/4 cup'),
(6, (SELECT id FROM ingredients WHERE name = 'garlic'), '4 cloves'),
(6, (SELECT id FROM ingredients WHERE name = 'oregano'), '2 tablespoons'),
(6, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '4 medium'),
(6, (SELECT id FROM ingredients WHERE name = 'olives'), '1/2 cup'),
(6, (SELECT id FROM ingredients WHERE name = 'feta cheese'), '200g'),

-- Recipe 7: Homemade Pizza
(7, (SELECT id FROM ingredients WHERE name = 'flour'), '3 cups'),
(7, (SELECT id FROM ingredients WHERE name = 'yeast'), '2 teaspoons'),
(7, (SELECT id FROM ingredients WHERE name = 'olive oil'), '2 tablespoons'),
(7, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '2 cans'),
(7, (SELECT id FROM ingredients WHERE name = 'mozzarella'), '300g'),
(7, (SELECT id FROM ingredients WHERE name = 'basil'), '1 bunch'),
(7, (SELECT id FROM ingredients WHERE name = 'garlic'), '3 cloves'),
(7, (SELECT id FROM ingredients WHERE name = 'oregano'), '1 tablespoon'),

-- Recipe 8: Indian Butter Chicken
(8, (SELECT id FROM ingredients WHERE name = 'chicken breast'), '1kg'),
(8, (SELECT id FROM ingredients WHERE name = 'yogurt'), '1 cup'),
(8, (SELECT id FROM ingredients WHERE name = 'butter'), '200g'),
(8, (SELECT id FROM ingredients WHERE name = 'cream'), '1 cup'),
(8, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '6 large'),
(8, (SELECT id FROM ingredients WHERE name = 'ginger'), '2 tablespoons'),
(8, (SELECT id FROM ingredients WHERE name = 'garlic'), '6 cloves'),
(8, (SELECT id FROM ingredients WHERE name = 'garam masala'), '2 tablespoons'),

-- Recipe 9: Mexican Enchiladas
(9, (SELECT id FROM ingredients WHERE name = 'tortillas'), '12'),
(9, (SELECT id FROM ingredients WHERE name = 'chicken breast'), '500g'),
(9, (SELECT id FROM ingredients WHERE name = 'cheese'), '300g'),
(9, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '4 large'),
(9, (SELECT id FROM ingredients WHERE name = 'onion'), '2 medium'),
(9, (SELECT id FROM ingredients WHERE name = 'garlic'), '4 cloves'),
(9, (SELECT id FROM ingredients WHERE name = 'cumin'), '2 teaspoons'),
(9, (SELECT id FROM ingredients WHERE name = 'chili powder'), '2 tablespoons'),

-- Recipe 10: Greek Moussaka
(10, (SELECT id FROM ingredients WHERE name = 'eggplant'), '3 large'),
(10, (SELECT id FROM ingredients WHERE name = 'ground beef'), '750g'),
(10, (SELECT id FROM ingredients WHERE name = 'onion'), '2 large'),
(10, (SELECT id FROM ingredients WHERE name = 'garlic'), '4 cloves'),
(10, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '2 cans'),
(10, (SELECT id FROM ingredients WHERE name = 'cinnamon'), '1 teaspoon'),
(10, (SELECT id FROM ingredients WHERE name = 'nutmeg'), '1/2 teaspoon'),
(10, (SELECT id FROM ingredients WHERE name = 'bechamel sauce'), '2 cups'),

-- Recipe 11: Japanese Ramen
(11, (SELECT id FROM ingredients WHERE name = 'ramen noodles'), '4 portions'),
(11, (SELECT id FROM ingredients WHERE name = 'pork belly'), '400g'),
(11, (SELECT id FROM ingredients WHERE name = 'soy sauce'), '1/4 cup'),
(11, (SELECT id FROM ingredients WHERE name = 'mirin'), '2 tablespoons'),
(11, (SELECT id FROM ingredients WHERE name = 'eggs'), '4'),
(11, (SELECT id FROM ingredients WHERE name = 'green onions'), '1 bunch'),
(11, (SELECT id FROM ingredients WHERE name = 'nori'), '4 sheets'),
(11, (SELECT id FROM ingredients WHERE name = 'bamboo shoots'), '1 can'),

-- Recipe 12: Moroccan Tagine
(12, (SELECT id FROM ingredients WHERE name = 'lamb'), '1kg'),
(12, (SELECT id FROM ingredients WHERE name = 'onion'), '2 large'),
(12, (SELECT id FROM ingredients WHERE name = 'garlic'), '6 cloves'),
(12, (SELECT id FROM ingredients WHERE name = 'carrots'), '4 large'),
(12, (SELECT id FROM ingredients WHERE name = 'chickpeas'), '1 can'),
(12, (SELECT id FROM ingredients WHERE name = 'dates'), '200g'),
(12, (SELECT id FROM ingredients WHERE name = 'cumin'), '2 teaspoons'),
(12, (SELECT id FROM ingredients WHERE name = 'coriander'), '2 teaspoons'),
(12, (SELECT id FROM ingredients WHERE name = 'cinnamon'), '1 teaspoon'),
(12, (SELECT id FROM ingredients WHERE name = 'saffron'), 'pinch'),

-- White Sauce Pasta
(13, (SELECT id FROM ingredients WHERE name = 'pasta'), '400g'),
(13, (SELECT id FROM ingredients WHERE name = 'butter'), '60g'),
(13, (SELECT id FROM ingredients WHERE name = 'flour'), '3 tablespoons'),
(13, (SELECT id FROM ingredients WHERE name = 'milk'), '2 cups'),
(13, (SELECT id FROM ingredients WHERE name = 'garlic'), '3 cloves'),
(13, (SELECT id FROM ingredients WHERE name = 'mushrooms'), '200g'),
(13, (SELECT id FROM ingredients WHERE name = 'parmesan cheese'), '1/2 cup'),
(13, (SELECT id FROM ingredients WHERE name = 'salt'), 'to taste'),
(13, (SELECT id FROM ingredients WHERE name = 'black pepper'), 'to taste'),
(13, (SELECT id FROM ingredients WHERE name = 'nutmeg'), '1/4 teaspoon'),

-- Marinara Pasta
(14, (SELECT id FROM ingredients WHERE name = 'pasta'), '400g'),
(14, (SELECT id FROM ingredients WHERE name = 'olive oil'), '1/4 cup'),
(14, (SELECT id FROM ingredients WHERE name = 'garlic'), '4 cloves'),
(14, (SELECT id FROM ingredients WHERE name = 'onion'), '1 medium'),
(14, (SELECT id FROM ingredients WHERE name = 'tomatoes'), '2 cans'),
(14, (SELECT id FROM ingredients WHERE name = 'fresh basil'), '1 cup'),  
(14, (SELECT id FROM ingredients WHERE name = 'dried basil'), '1 cup'),  
(14, (SELECT id FROM ingredients WHERE name = 'oregano'), '1 tablespoon'),
(14, (SELECT id FROM ingredients WHERE name = 'salt'), 'to taste'),
(14, (SELECT id FROM ingredients WHERE name = 'black pepper'), 'to taste'),
(14, (SELECT id FROM ingredients WHERE name = 'parmesan cheese'), '1/2 cup'),

-- Masala Dosa
(15, (SELECT id FROM ingredients WHERE name = 'rice'), '2 cups'),
(15, (SELECT id FROM ingredients WHERE name = 'potatoes'), '4 medium'),
(15, (SELECT id FROM ingredients WHERE name = 'onion'), '2 medium'),
(15, (SELECT id FROM ingredients WHERE name = 'mustard seeds'), '1 teaspoon'),
(15, (SELECT id FROM ingredients WHERE name = 'curry leaves'), '10'),
(15, (SELECT id FROM ingredients WHERE name = 'turmeric'), '1/2 teaspoon'),
(15, (SELECT id FROM ingredients WHERE name = 'salt'), 'to taste'),
(15, (SELECT id FROM ingredients WHERE name = 'oil'), '3 tablespoons');

-- Chicken Biryani
(16, (SELECT id FROM ingredients WHERE name = 'chicken'), '1 kg'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'rice'), '3 cups'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'yogurt'), '1 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'onion'), '3 large'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'ginger'), '2 tablespoons'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'garlic'), '8 cloves'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'saffron'), 'few strands'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'garam masala'), '2 tablespoons'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'mint'), '1 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'ghee'), '1/2 cup'),

-- Add ingredients for Rice Pudding
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity) VALUES
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'rice'), '1/2 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'milk'), '1 liter'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'sugar'), '1/2 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'cardamom'), '4-5 pods'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'almonds'), '1/4 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'raisins'), '2 tablespoons'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'saffron'), 'few strands'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'pistachios'), '2 tablespoons'),

((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'rice'), '1/2 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'milk'), '1 liter'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'sugar'), '1/2 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'cardamom'), '4-5 pods'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'almonds'), '1/4 cup'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'raisins'), '2 tablespoons'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'saffron'), 'few strands'),
((SELECT MAX(id) FROM recipes), (SELECT id FROM ingredients WHERE name = 'pistachios'), '2 tablespoons');

UPDATE recipes 
SET image_url = 'images/marina-pasta.jpg' 
WHERE title = 'Classic Marinara Pasta';

UPDATE recipes 
SET image_url = 'images/white-pasta.jpg' 
WHERE title = 'Creamy White Sauce Pasta';

UPDATE recipes 
SET image_url = 'images/mexican.jpg' 
WHERE title = 'Mexican Enchiladas';


UPDATE recipes 
SET image_url = 'images/butter-chicken.jpg' 
WHERE title = 'Indian Butter Chicken';

UPDATE recipes 
SET image_url = 'images/homemade_pizza.jpg' 
WHERE title = 'Homemade Pizza';

UPDATE recipes 
SET image_url = 'images/fish.jpg' 
WHERE title = 'Mediterranean Grilled Fish';